# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ced41afa213a92db9674fe43388c2224fadb565e261f48a254a6c5b3f8728cf4db039b98f14a1aa48f95447bd4e7746ce07f39aa354d7d6b999a417c743992b

test:
  secret_key_base: a00788341c2adbfad6299be8e262d3747c9f2dcc379294295f35bb51c70a2d191827bf8cf2805e349ffce51329f7141c316d7737dbc1235ad58ef7973228b24b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
